fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    hp: 'git://github.com/ghoneycutt/puppet-module-hp.git'
    psp: 'git://github.com/razorsedge/puppet-psp.git'
  symlinks:
    physical: "#{source_dir}"
